baseURL = 'https://joebyjo.dev/'
languageCode = 'en-us'
title = 'whois JoeByjo'
pagination.pagerSize = 7

[module]
  [[module.imports]]
    path = "github.com/joebyjo/wreck-it-ralph-hugo-theme/v2"

[params]
  logo = "JoeByjo"
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[params.umami]
  enabled = true
  script = "https://cloud.umami.is/script.js"
  websiteID = "86297ccd-3f7a-438b-af5b-e18f3985b724"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1